### ISSUE TITLE
Consider minor addition to color randomization

### ISSUE THREAD

**Issue by karenatalyants** [VarazdatStepanyan003/boardballmodel#1]
You may want to use a random hex color generator I wrote for my homework5, here it is

const colorRandomizer = function() {
      const hexColorArr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 'a', 'b', 'c', 'd', 'e', 'f'];
      let color = '#';
      const random15 = function(min, max) {
        min = Math.ceil(min);
        max = Math.floor(max);
        return Math.floor(Math.random() * (max - min + 1)) + min; 
      }
      for (let j = 1; j <= 6; j++) {
        color = color + hexColorArr[random15(0, 15)];
      }
      return color;
    };

**Comment by VarazdatStepanyan003** [comment]
awesome idea but you could do it easier just writing

color="#"+rand(Math.pow(16,6)).toString(16);
